def build_registry(NodeTypeEnum, _node, _spec):
    T = NodeTypeEnum
    registry = {}

    registry.update({
        "CSVParser": _node(
            name="CSVParser",
            description="Reads a CSV file from disk and returns a DataFrame",
            input_type=T.FILE_PATH,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/csv_parser.py",
            function_name="csv_parser",
            domain="pandas",
            category="source",
            keywords=["csv", "read csv", "load csv"],
            param_schema={"file_path": _spec("str", required=True)},
            is_source=True,
            allow_extra_params=False,
        ),
        "JSONParser": _node(
            name="JSONParser",
            description="Reads a JSON file from disk and returns a DataFrame",
            input_type=T.FILE_PATH,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/json_parser.py",
            function_name="json_parser",
            domain="pandas",
            category="source",
            keywords=["json", "read json", "load json"],
            param_schema={"file_path": _spec("str", required=True)},
            is_source=True,
            allow_extra_params=False,
        ),
        "ExcelParser": _node(
            name="ExcelParser",
            description="Reads an Excel file from disk and returns a DataFrame",
            input_type=T.FILE_PATH,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/excel_parser.py",
            function_name="excel_parser",
            domain="pandas",
            category="source",
            keywords=["excel", "xlsx", "read excel"],
            param_schema={"file_path": _spec("str", required=True)},
            is_source=True,
            allow_extra_params=False,
        ),
        "DataFrameInput": _node(
            name="DataFrameInput",
            description="Loads an in-memory DataFrame from runtime context",
            input_type=T.ANY,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/dataframe_input.py",
            function_name="dataframe_input",
            domain="pandas",
            category="source",
            keywords=["dataframe", "df", "in-memory frame"],
            param_schema={
                "dataframe": _spec("any", allow_none=True),
                "source_name": _spec("str"),
                "copy": _spec("bool"),
            },
            is_source=True,
            allow_extra_params=False,
        ),
        "SchemaValidator": _node(
            name="SchemaValidator",
            description="Validates that required columns exist and optionally checks dtypes",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/schema_validator.py",
            function_name="schema_validator",
            domain="pandas",
            category="validation",
            keywords=["schema", "validate columns", "dtype check"],
            param_schema={"schema": _spec("dict")},
            allow_extra_params=False,
        ),
        "RenameColumns": _node(
            name="RenameColumns",
            description="Renames DataFrame columns using a mapping",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/rename_columns.py",
            function_name="rename_columns",
            domain="pandas",
            category="column_op",
            keywords=["rename columns", "rename fields"],
            param_schema={"columns": _spec("dict", required=True)},
            allow_extra_params=False,
        ),
        "DataFilter": _node(
            name="DataFilter",
            description="Filters rows using a pandas query expression",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/data_filter.py",
            function_name="data_filter",
            domain="pandas",
            category="row_op",
            keywords=["filter rows", "where clause", "query"],
            param_schema={"condition": _spec("str", required=True)},
            allow_extra_params=False,
        ),
        "ColumnSelector": _node(
            name="ColumnSelector",
            description="Selects a specific list of columns from a DataFrame",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/column_selector.py",
            function_name="column_selector",
            domain="pandas",
            category="column_op",
            keywords=["select columns", "project columns", "keep columns"],
            param_schema={"columns": _spec("list", required=True, item_types=["str"], min_items=1)},
            allow_extra_params=False,
        ),
        "DropNulls": _node(
            name="DropNulls",
            description="Drops rows with missing values",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/drop_nulls.py",
            function_name="drop_nulls",
            domain="pandas",
            category="null_op",
            keywords=["drop nulls", "drop na", "remove missing rows"],
            param_schema={
                "subset": _spec("list", item_types=["str"], min_items=1),
                "how": _spec("str", choices=["any", "all"]),
            },
            allow_extra_params=False,
        ),
        "FillNulls": _node(
            name="FillNulls",
            description="Fills missing values with a scalar or mapping",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/fill_nulls.py",
            function_name="fill_nulls",
            domain="pandas",
            category="null_op",
            keywords=["fill nulls", "impute", "fillna"],
            param_schema={
                "values": _spec("any", required=True),
                "columns": _spec("list", item_types=["str"], min_items=1),
            },
            allow_extra_params=False,
        ),
        "DataSorter": _node(
            name="DataSorter",
            description="Sorts rows by one or more columns",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/data_sorter.py",
            function_name="data_sorter",
            domain="pandas",
            category="row_op",
            keywords=["sort rows", "order rows", "sort values"],
            param_schema={
                "by": _spec("str", "list", required=True, item_types=["str"], min_items=1),
                "ascending": _spec("bool", "list", required=True, item_types=["bool"], min_items=1),
            },
            allow_extra_params=False,
        ),
        "TypeCaster": _node(
            name="TypeCaster",
            description="Casts one or more DataFrame columns to target dtypes",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/type_caster.py",
            function_name="type_caster",
            domain="pandas",
            category="column_op",
            keywords=["cast columns", "astype", "convert dtype"],
            param_schema={"mapping": _spec("dict", required=True)},
            allow_extra_params=False,
        ),
        "DataDeduplicator": _node(
            name="DataDeduplicator",
            description="Drops duplicate rows, optionally using a subset of columns",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/data_deduplicator.py",
            function_name="data_deduplicator",
            domain="pandas",
            category="row_op",
            keywords=["drop duplicates", "deduplicate", "unique rows"],
            param_schema={
                "subset": _spec("list", item_types=["str"], min_items=1),
                "keep": _spec("str", choices=["first", "last", False]),
                "ignore_index": _spec("bool"),
            },
            allow_extra_params=False,
        ),
    })

    registry.update({
        "AddConstantColumn": _node(
            name="AddConstantColumn",
            description="Creates or overwrites a column with a constant value",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/add_constant_column.py",
            function_name="add_constant_column",
            domain="pandas",
            category="column_op",
            keywords=["constant column", "literal column", "assign constant"],
            param_schema={
                "column": _spec("str", required=True),
                "value": _spec("any", required=True),
            },
            allow_extra_params=False,
        ),
        "ArithmeticColumn": _node(
            name="ArithmeticColumn",
            description="Creates a column from arithmetic on two operands",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/arithmetic_column.py",
            function_name="arithmetic_column",
            domain="pandas",
            category="column_op",
            keywords=["arithmetic column", "add columns", "subtract columns", "multiply columns"],
            param_schema={
                "target": _spec("str", required=True),
                "left": _spec("any", required=True),
                "op": _spec("str", required=True, choices=["+", "-", "*", "/", "//", "%", "**"]),
                "right": _spec("any", required=True),
            },
            allow_extra_params=False,
        ),
        "MapColumn": _node(
            name="MapColumn",
            description="Maps values from a source column through a dictionary",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/map_column.py",
            function_name="map_column",
            domain="pandas",
            category="column_op",
            keywords=["map column", "lookup mapping", "replace values by dict"],
            param_schema={
                "source": _spec("str", required=True),
                "target": _spec("str", required=True),
                "mapping": _spec("dict", required=True),
                "default": _spec("any"),
            },
            allow_extra_params=False,
        ),
        "WhereColumn": _node(
            name="WhereColumn",
            description="Applies pandas where semantics to a source column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/where_column.py",
            function_name="where_column",
            domain="pandas",
            category="column_op",
            keywords=["where column", "conditional keep", "conditional replace"],
            param_schema={
                "source": _spec("str", required=True),
                "target": _spec("str", required=True),
                "condition": _spec("str", required=True),
                "other": _spec("any", required=True),
            },
            allow_extra_params=False,
        ),
        "MaskColumn": _node(
            name="MaskColumn",
            description="Applies pandas mask semantics to a source column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/mask_column.py",
            function_name="mask_column",
            domain="pandas",
            category="column_op",
            keywords=["mask column", "replace when condition", "conditional overwrite"],
            param_schema={
                "source": _spec("str", required=True),
                "target": _spec("str", required=True),
                "condition": _spec("str", required=True),
                "value": _spec("any", required=True),
            },
            allow_extra_params=False,
        ),
        "CoalesceColumns": _node(
            name="CoalesceColumns",
            description="Creates a target column from the first non-null value across source columns",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/coalesce_columns.py",
            function_name="coalesce_columns",
            domain="pandas",
            category="column_op",
            keywords=["coalesce columns", "fill from other columns", "combine first non-null"],
            param_schema={
                "target": _spec("str", required=True),
                "sources": _spec("list", required=True, item_types=["str"], min_items=1),
            },
            allow_extra_params=False,
        ),
        "StripText": _node(
            name="StripText",
            description="Strips whitespace or characters from a text column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/strip_text.py",
            function_name="strip_text",
            domain="pandas",
            category="string_op",
            keywords=["strip text", "trim text", "remove whitespace"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str"),
                "chars": _spec("str"),
            },
            allow_extra_params=False,
        ),
        "LowerText": _node(
            name="LowerText",
            description="Lowercases a text column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/lower_text.py",
            function_name="lower_text",
            domain="pandas",
            category="string_op",
            keywords=["lower text", "lowercase"],
            param_schema={"column": _spec("str", required=True), "target": _spec("str")},
            allow_extra_params=False,
        ),
        "UpperText": _node(
            name="UpperText",
            description="Uppercases a text column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/upper_text.py",
            function_name="upper_text",
            domain="pandas",
            category="string_op",
            keywords=["upper text", "uppercase"],
            param_schema={"column": _spec("str", required=True), "target": _spec("str")},
            allow_extra_params=False,
        ),
        "ReplaceText": _node(
            name="ReplaceText",
            description="Replaces text in a column using pandas string replace",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/replace_text.py",
            function_name="replace_text",
            domain="pandas",
            category="string_op",
            keywords=["replace text", "regex replace", "string replace"],
            param_schema={
                "column": _spec("str", required=True),
                "pattern": _spec("str", required=True),
                "repl": _spec("str", required=True),
                "target": _spec("str"),
                "n": _spec("int"),
                "case": _spec("bool"),
                "regex": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "SplitText": _node(
            name="SplitText",
            description="Splits a text column into lists or expanded output columns",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/split_text.py",
            function_name="split_text",
            domain="pandas",
            category="string_op",
            keywords=["split text", "tokenize column", "split string"],
            param_schema={
                "column": _spec("str", required=True),
                "pattern": _spec("str"),
                "target": _spec("str"),
                "targets": _spec("list", item_types=["str"], min_items=1),
                "n": _spec("int"),
                "regex": _spec("bool"),
                "expand": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ExtractText": _node(
            name="ExtractText",
            description="Extracts regex capture groups from a text column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/extract_text.py",
            function_name="extract_text",
            domain="pandas",
            category="string_op",
            keywords=["extract text", "regex extract", "capture groups"],
            param_schema={
                "column": _spec("str", required=True),
                "pattern": _spec("str", required=True),
                "target": _spec("str"),
                "targets": _spec("list", item_types=["str"], min_items=1),
                "flags": _spec("int"),
            },
            allow_extra_params=False,
        ),
        "ContainsText": _node(
            name="ContainsText",
            description="Computes a boolean column from text containment",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/contains_text.py",
            function_name="contains_text",
            domain="pandas",
            category="string_op",
            keywords=["contains text", "string contains", "regex contains"],
            param_schema={
                "column": _spec("str", required=True),
                "pattern": _spec("str", required=True),
                "target": _spec("str"),
                "case": _spec("bool"),
                "regex": _spec("bool"),
                "na": _spec("any"),
            },
            allow_extra_params=False,
        ),
    })

    registry.update({
        "ToDatetime": _node(
            name="ToDatetime",
            description="Parses a column into pandas datetime values",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/to_datetime.py",
            function_name="to_datetime",
            domain="pandas",
            category="datetime_op",
            keywords=["to datetime", "parse dates", "convert datetime"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str"),
                "format": _spec("str"),
                "errors": _spec("str"),
                "utc": _spec("bool"),
                "dayfirst": _spec("bool"),
                "yearfirst": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ExtractYear": _node(
            name="ExtractYear",
            description="Extracts the year from a datetime-like column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/extract_year.py",
            function_name="extract_year",
            domain="pandas",
            category="datetime_op",
            keywords=["extract year", "year part"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str"),
                "format": _spec("str"),
                "errors": _spec("str"),
                "utc": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ExtractMonth": _node(
            name="ExtractMonth",
            description="Extracts the month from a datetime-like column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/extract_month.py",
            function_name="extract_month",
            domain="pandas",
            category="datetime_op",
            keywords=["extract month", "month part"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str"),
                "format": _spec("str"),
                "errors": _spec("str"),
                "utc": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ExtractDay": _node(
            name="ExtractDay",
            description="Extracts the day of month from a datetime-like column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/extract_day.py",
            function_name="extract_day",
            domain="pandas",
            category="datetime_op",
            keywords=["extract day", "day part"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str"),
                "format": _spec("str"),
                "errors": _spec("str"),
                "utc": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "DateDiff": _node(
            name="DateDiff",
            description="Computes differences between two datetime-like columns",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/date_diff.py",
            function_name="date_diff",
            domain="pandas",
            category="datetime_op",
            keywords=["date diff", "date difference", "timedelta"],
            param_schema={
                "start": _spec("str", required=True),
                "end": _spec("str", required=True),
                "target": _spec("str", required=True),
                "unit": _spec("str", choices=["timedelta", "days", "hours", "minutes", "seconds"]),
                "absolute": _spec("bool"),
                "format": _spec("str"),
                "errors": _spec("str"),
                "utc": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "GroupByAgg": _node(
            name="GroupByAgg",
            description="Groups by one or more keys and applies named aggregations",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/group_by_agg.py",
            function_name="group_by_agg",
            domain="pandas",
            category="aggregation",
            keywords=["group by", "aggregate", "named aggregations"],
            param_schema={
                "group_by": _spec("str", "list", required=True, item_types=["str"], min_items=1),
                "aggregations": _spec("list", "dict", required=True),
                "sort": _spec("bool"),
                "dropna": _spec("bool"),
                "observed": _spec("bool"),
                "as_index": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "PivotFrame": _node(
            name="PivotFrame",
            description="Pivots a DataFrame into wide format",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/pivot_frame.py",
            function_name="pivot_frame",
            domain="pandas",
            category="reshape_op",
            keywords=["pivot", "wide format"],
            param_schema={
                "index": _spec("str", "list", required=True, item_types=["str"], min_items=1),
                "columns": _spec("str", "list", required=True, item_types=["str"], min_items=1),
                "values": _spec("str", "list", item_types=["str"], min_items=1),
                "reset_index": _spec("bool"),
                "flatten_columns": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "PivotTableFrame": _node(
            name="PivotTableFrame",
            description="Builds a pivot table with an aggregation function",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/pivot_table_frame.py",
            function_name="pivot_table_frame",
            domain="pandas",
            category="reshape_op",
            keywords=["pivot table", "aggregate pivot"],
            param_schema={
                "index": _spec("str", "list", item_types=["str"], min_items=1),
                "columns": _spec("str", "list", item_types=["str"], min_items=1),
                "values": _spec("str", "list", item_types=["str"], min_items=1),
                "aggfunc": _spec("any"),
                "fill_value": _spec("any"),
                "margins": _spec("bool"),
                "dropna": _spec("bool"),
                "observed": _spec("bool"),
                "reset_index": _spec("bool"),
                "flatten_columns": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "MeltFrame": _node(
            name="MeltFrame",
            description="Melts a DataFrame from wide format to long format",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/melt_frame.py",
            function_name="melt_frame",
            domain="pandas",
            category="reshape_op",
            keywords=["melt", "long format", "unpivot"],
            param_schema={
                "id_vars": _spec("str", "list", item_types=["str"], min_items=1),
                "value_vars": _spec("str", "list", item_types=["str"], min_items=1),
                "var_name": _spec("str"),
                "value_name": _spec("str"),
                "ignore_index": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ExplodeColumn": _node(
            name="ExplodeColumn",
            description="Explodes list-like values from a column into multiple rows",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/explode_column.py",
            function_name="explode_column",
            domain="pandas",
            category="reshape_op",
            keywords=["explode", "unnest list column"],
            param_schema={
                "column": _spec("str", required=True),
                "ignore_index": _spec("bool"),
            },
            allow_extra_params=False,
        ),
    })

    registry.update({
        "SetIndex": _node(
            name="SetIndex",
            description="Sets one or more columns as the DataFrame index",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/set_index.py",
            function_name="set_index",
            domain="pandas",
            category="index_op",
            keywords=["set index", "index columns"],
            param_schema={
                "keys": _spec("str", "list", required=True, item_types=["str"], min_items=1),
                "drop": _spec("bool"),
                "append": _spec("bool"),
                "verify_integrity": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ResetIndex": _node(
            name="ResetIndex",
            description="Resets the DataFrame index back to columns",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/reset_index.py",
            function_name="reset_index",
            domain="pandas",
            category="index_op",
            keywords=["reset index"],
            param_schema={
                "level": _spec("any"),
                "drop": _spec("bool"),
                "names": _spec("str", "list", item_types=["str"], min_items=1),
            },
            allow_extra_params=False,
        ),
        "SortIndex": _node(
            name="SortIndex",
            description="Sorts a DataFrame by its index",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/sort_index.py",
            function_name="sort_index",
            domain="pandas",
            category="index_op",
            keywords=["sort index"],
            param_schema={
                "axis": _spec("int"),
                "level": _spec("any"),
                "ascending": _spec("bool"),
                "na_position": _spec("str", choices=["first", "last"]),
                "sort_remaining": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ReindexFrame": _node(
            name="ReindexFrame",
            description="Reindexes rows or columns to a new label set",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/reindex_frame.py",
            function_name="reindex_frame",
            domain="pandas",
            category="index_op",
            keywords=["reindex", "align index", "reorder labels"],
            param_schema={
                "index": _spec("list", item_types=["any"], min_items=1),
                "columns": _spec("list", item_types=["str"], min_items=1),
                "fill_value": _spec("any"),
                "fill_method": _spec("str"),
                "copy": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ValueCountsOps": _node(
            name="ValueCountsOps",
            description="Computes value counts for one or more columns",
            input_type=T.DATA_FRAME,
            output_type=T.SERIES,
            template_path="nodes/templates/value_counts_ops.py",
            function_name="value_counts_ops",
            domain="pandas",
            category="aggregation",
            keywords=["value counts", "frequency counts", "normalized counts"],
            param_schema={
                "column": _spec("str", "list", required=True, item_types=["str"], min_items=1),
                "normalize": _spec("bool"),
                "sort": _spec("bool"),
                "ascending": _spec("bool"),
                "dropna": _spec("bool"),
                "top_k": _spec("int"),
                "name": _spec("str"),
            },
            allow_extra_params=False,
        ),
        "RankValues": _node(
            name="RankValues",
            description="Ranks values within the whole frame or within groups",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/rank_values.py",
            function_name="rank_values",
            domain="pandas",
            category="window_op",
            keywords=["rank", "dense rank", "window rank"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str", required=True),
                "group_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_ascending": _spec("bool"),
                "method": _spec("str"),
                "ascending": _spec("bool"),
                "pct": _spec("bool"),
                "dropna": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "CumulativeSum": _node(
            name="CumulativeSum",
            description="Computes a cumulative sum over a column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/cumulative_sum.py",
            function_name="cumulative_sum",
            domain="pandas",
            category="window_op",
            keywords=["cumsum", "cumulative sum", "running total"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str", required=True),
                "group_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_ascending": _spec("bool"),
                "dropna": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "CumulativeCount": _node(
            name="CumulativeCount",
            description="Computes a cumulative row count over the frame or within groups",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/cumulative_count.py",
            function_name="cumulative_count",
            domain="pandas",
            category="window_op",
            keywords=["cumcount", "cumulative count", "running count"],
            param_schema={
                "target": _spec("str", required=True),
                "group_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_ascending": _spec("bool"),
                "ascending": _spec("bool"),
                "dropna": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "RollingAggregate": _node(
            name="RollingAggregate",
            description="Computes a rolling aggregation over a column",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/rolling_aggregate.py",
            function_name="rolling_aggregate",
            domain="pandas",
            category="window_op",
            keywords=["rolling", "moving average", "rolling aggregate"],
            param_schema={
                "column": _spec("str", required=True),
                "target": _spec("str", required=True),
                "window": _spec("int", required=True),
                "group_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_by": _spec("str", "list", item_types=["str"], min_items=1),
                "sort_ascending": _spec("bool"),
                "min_periods": _spec("int"),
                "center": _spec("bool"),
                "agg": _spec("any"),
                "dropna": _spec("bool"),
            },
            allow_extra_params=False,
        ),
        "ReduceOutput": _node(
            name="ReduceOutput",
            description="Reduces a DataFrame or Series to a DataFrame, Series, or scalar",
            input_type=T.ANY,
            output_type=T.ANY,
            template_path="nodes/templates/reduce_output.py",
            function_name="reduce_output",
            domain="pandas",
            category="reduce_op",
            keywords=["final result", "reduce output", "scalar output"],
            param_schema={
                "method": _spec("str"),
                "column": _spec("str"),
                "row": _spec("any"),
                "label": _spec("any"),
                "position": _spec("int"),
                "n": _spec("int"),
                "agg": _spec("str"),
            },
            allow_extra_params=True,
        ),
        "StatsSummary": _node(
            name="StatsSummary",
            description="Computes descriptive statistics for a DataFrame",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/stats_summary.py",
            function_name="stats_summary",
            domain="pandas",
            category="summary",
            keywords=["describe", "summary statistics"],
            param_schema={},
            allow_extra_params=False,
        ),
        "DataFrameJoin": _node(
            name="DataFrameJoin",
            description="Joins two DataFrames on a key",
            input_type=T.DATA_FRAME,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/dataframe_join.py",
            function_name="dataframe_join",
            domain="pandas",
            category="join",
            keywords=["join dataframes", "merge frames"],
            param_schema={
                "on": _spec("str", required=True),
                "how": _spec("str", required=True, choices=["inner", "left", "right", "outer"]),
            },
            planner_enabled=False,
            allow_extra_params=False,
        ),
    })

    registry.update({
        "SQLiteConnector": _node(
            name="SQLiteConnector",
            description="Stores a DataFrame into a SQLite database table",
            input_type=T.DATA_FRAME,
            output_type=T.DB_HANDLE,
            template_path="nodes/templates/sqlite_connector.py",
            function_name="sqlite_connector",
            domain="storage",
            category="storage",
            keywords=["sqlite", "write sqlite", "store table"],
            param_schema={
                "db_path": _spec("str", required=True),
                "table_name": _spec("str", required=True),
            },
            allow_extra_params=False,
        ),
        "SQLiteReader": _node(
            name="SQLiteReader",
            description="Connects to an existing SQLite database and returns a DB handle",
            input_type=T.FILE_PATH,
            output_type=T.DB_HANDLE,
            template_path="nodes/templates/sqlite_reader.py",
            function_name="sqlite_reader",
            domain="storage",
            category="storage",
            keywords=["sqlite", "open sqlite", "database handle"],
            param_schema={"db_path": _spec("str", required=True)},
            is_source=True,
            allow_extra_params=False,
        ),
        "PostgresConnector": _node(
            name="PostgresConnector",
            description="Stores a DataFrame into a PostgreSQL database table",
            input_type=T.DATA_FRAME,
            output_type=T.DB_HANDLE,
            template_path="nodes/templates/postgres_connector.py",
            function_name="postgres_connector",
            domain="storage",
            category="storage",
            keywords=["postgres", "postgresql", "write postgres"],
            param_schema={
                "connection_string": _spec("str", required=True),
                "table_name": _spec("str", required=True),
            },
            allow_extra_params=False,
        ),
        "QueryEngine": _node(
            name="QueryEngine",
            description="Runs SQL queries against a DBHandle and returns a DataFrame",
            input_type=T.DB_HANDLE,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/query_engine.py",
            function_name="query_engine",
            domain="sql",
            category="query",
            keywords=["sql query", "select from db", "query database"],
            param_schema={"query": _spec("str", required=True)},
            allow_extra_params=False,
        ),
        "CSVExporter": _node(
            name="CSVExporter",
            description="Exports a DataFrame to a CSV file",
            input_type=T.DATA_FRAME,
            output_type=T.FILE_PATH,
            template_path="nodes/templates/csv_exporter.py",
            function_name="csv_exporter",
            domain="export",
            category="export",
            keywords=["write csv", "export csv"],
            param_schema={"output_path": _spec("str", required=True)},
            accepted_input_types=[T.DATA_FRAME, T.SERIES],
            allow_extra_params=False,
        ),
        "JSONExporter": _node(
            name="JSONExporter",
            description="Exports a DataFrame to a JSON file",
            input_type=T.DATA_FRAME,
            output_type=T.FILE_PATH,
            template_path="nodes/templates/json_exporter.py",
            function_name="json_exporter",
            domain="export",
            category="export",
            keywords=["write json", "export json"],
            param_schema={"output_path": _spec("str", required=True)},
            accepted_input_types=[T.DATA_FRAME, T.SERIES],
            allow_extra_params=False,
        ),
        "RESTEndpoint": _node(
            name="RESTEndpoint",
            description="Exposes a DBHandle as a REST API endpoint using Flask",
            input_type=T.DB_HANDLE,
            output_type=T.HTTP_RESPONSE,
            template_path="nodes/templates/rest_endpoint.py",
            function_name="rest_endpoint",
            domain="api",
            category="api",
            keywords=["rest endpoint", "flask api", "serve database"],
            param_schema={
                "route": _spec("str", required=True),
                "port": _spec("int", required=True),
            },
            allow_extra_params=False,
        ),
        "AuthMiddleware": _node(
            name="AuthMiddleware",
            description="Adds API key authentication to an HTTP endpoint",
            input_type=T.HTTP_RESPONSE,
            output_type=T.HTTP_RESPONSE,
            template_path="nodes/templates/auth_middleware.py",
            function_name="auth_middleware",
            domain="api",
            category="api",
            keywords=["api auth", "api key"],
            param_schema={"api_key_env_var": _spec("str", required=True)},
            allow_extra_params=False,
        ),
        "ErrorHandler": _node(
            name="ErrorHandler",
            description="Wraps output generation in structured error handling",
            input_type=T.ANY,
            output_type=T.HTTP_RESPONSE,
            template_path="nodes/templates/error_handler.py",
            function_name="error_handler",
            domain="api",
            category="api",
            keywords=["error handling", "try except"],
            param_schema={},
            allow_extra_params=False,
        ),
        "Logger": _node(
            name="Logger",
            description="Logs intermediate data without modifying it",
            input_type=T.ANY,
            output_type=T.ANY,
            template_path="nodes/templates/logger.py",
            function_name="logger",
            domain="observability",
            category="observability",
            keywords=["log data", "debug output"],
            param_schema={},
            allow_extra_params=False,
        ),
        "HTTPToDataFrame": _node(
            name="HTTPToDataFrame",
            description="Converts an HTTP JSON response into a DataFrame",
            input_type=T.HTTP_RESPONSE,
            output_type=T.DATA_FRAME,
            template_path="nodes/templates/http_to_dataframe.py",
            function_name="http_to_dataframe",
            domain="adapter",
            category="adapter",
            keywords=["http to dataframe", "json response to frame"],
            param_schema={},
            allow_extra_params=False,
        ),
    })

    return registry
