import os
from collections import Counter, defaultdict
from core.plan_utils import normalize_plan_shape
from nodes.registry import NODE_REGISTRY
from core.validator import validate_plan, topological_sort


def _build_output_vars(nodes: list[dict[str, str]]) -> dict[str, str]:
    type_counts = Counter(node["type"] for node in nodes)
    seen_counts = defaultdict(int)
    output_var_by_id = {}

    for node in nodes:
        node_id = node["id"]
        node_type = node["type"]
        func_name = NODE_REGISTRY[node_type].function_name
        seen_counts[node_type] += 1

        if type_counts[node_type] == 1:
            output_var_by_id[node_id] = f"out_{func_name}"
        else:
            output_var_by_id[node_id] = f"out_{func_name}_{seen_counts[node_type]}"

    return output_var_by_id


def auto_glue_code(
    ordered_node_ids: list[str],
    edges: list,
    parameters: dict,
    node_type_by_id: dict[str, str],
    output_var_by_id: dict[str, str],
    emit_mode: str = "print",
    result_variable: str = "result",
) -> str:
    predecessor = {}
    for source, target in edges:
        predecessor[target] = source

    lines = []
    lines.append("if __name__ == '__main__':")

    for node_id in ordered_node_ids:
        node_type = node_type_by_id[node_id]
        func_name = NODE_REGISTRY[node_type].function_name
        out_var = output_var_by_id[node_id]
        params = parameters.get(node_id, {})

        args = []

        # Pass previous node output
        if node_id in predecessor:
            pred = predecessor[node_id]
            args.append(output_var_by_id[pred])

        # Pass explicit parameters safely
        for key, value in params.items():
            args.append(f"{key}={repr(value)}")

        arg_str = ", ".join(args)
        lines.append(f"    {out_var} = {func_name}({arg_str})")

    last_var = output_var_by_id[ordered_node_ids[-1]]
    if emit_mode == "print":
        lines.append(f"    print({last_var})")
    elif emit_mode == "result":
        lines.append(f"    {result_variable} = {last_var}")
    else:
        raise ValueError(f"Unsupported emit_mode: {emit_mode}")

    return "\n".join(lines)


def compile_output(plan: dict, *, emit_mode: str = "print", result_variable: str = "result") -> str:
    plan = normalize_plan_shape(plan)
    is_valid, errors = validate_plan(plan)

    if not is_valid:
        raise ValueError("Invalid plan:\n" + "\n".join(errors))

    nodes = plan.get("nodes", [])
    edges = plan.get("edges", [])
    parameters = plan.get("parameters", {})
    node_ids = [node["id"] for node in nodes]
    node_type_by_id = {node["id"]: node["type"] for node in nodes}
    output_var_by_id = _build_output_vars(nodes)

    ordered_node_ids = topological_sort(node_ids, edges)
    glue_code = plan.get("glue_code", "").strip()

    output_parts: list[str] = []

    output_parts.append("# Generated by PlanCompiler")
    output_parts.append("# DO NOT EDIT MANUALLY\n")

    emitted_types = set()
    for node_id in ordered_node_ids:
        node_type = node_type_by_id[node_id]
        if node_type in emitted_types:
            continue

        emitted_types.add(node_type)
        node = NODE_REGISTRY[node_type]
        template_path = node.template_path

        if not os.path.exists(template_path):
            raise FileNotFoundError(
                f"Template not found for node '{node_type}': {template_path}"
            )

        with open(template_path, "r", encoding="utf-8") as f:
            template_code = f.read()

        output_parts.append(f"# --- Node Type: {node_type} ---")
        output_parts.append(template_code.strip() + "\n")
        output_parts.append("")

    if glue_code:
        output_parts.append("# --- Execution (LLM-generated) ---")
        output_parts.append(glue_code)
    else:
        output_parts.append("# --- Execution (auto-generated) ---")
        output_parts.append(
            auto_glue_code(
                ordered_node_ids,
                edges,
                parameters,
                node_type_by_id,
                output_var_by_id,
                emit_mode=emit_mode,
                result_variable=result_variable,
            )
        )

    return "\n".join(output_parts)


def write_output(code: str, path: str = "output/app.py") -> None:
    os.makedirs("output", exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write(code)

    with open("output/requirements.txt", "w", encoding="utf-8") as f:
        f.write("flask\npandas\n")

    print(f"Emitted: {path}")
    print("Emitted: output/requirements.txt")
